spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 49.235.140.112:8848
    gateway:
      routes:
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - path=/api/mall-ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: member-route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: member-route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:

            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}



logging:
  level:
    org.springframework.cloud.gateway: trace
server:
  port: 88