##端口号
server:
  port: 10000
#配置数据源
spring:
  cache:
    type: redis
    redis:
      use-key-prefix: true
      cache-null-values: true
  redis:
    host: 139.196.92.81
    port: 6380
    password: 271886
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: root
    url: jdbc:mysql://49.235.140.112:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  #注册中心地址
  cloud:
    nacos:
      config:
        server-addr: 49.235.140.112:8848
        username: nacos
        password: nacos
      discovery:
        server-addr: 49.235.140.112:8848
        username: nacos
        password: nacos
  #服务名
  application:
    name: mall-product

#mybatis-plus映射文件
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:   #配置每个实体类的主键自增长
    db-config:
      id-type: auto
logging:
  level:
    com.hc.mall: debug