##端口号
server:
  port: 9000

#配置数据源
spring:
  redis:
    port: 6380
    host: 139.196.92.81
  rabbitmq:
    host: 49.235.140.112
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
  datasource:
    username: root
    password: root
    url: jdbc:mysql://49.235.140.112:3306/mall_oms?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  #注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 49.235.140.112:8848
  #服务名
  application:
    name: mall-order

#mybatis-plus映射文件
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:   #配置每个实体类的主键自增长
    db-config:
      id-type: auto


mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
